# Generated by Django 4.2.7 on 2023-11-04 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='word_content',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
