# Generated by Django 4.2.7 on 2023-11-04 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_word_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='word_content',
            new_name='word_count',
        ),
    ]
